# Generated by Django 4.2.7 on 2023-11-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('img', models.URLField(verbose_name='Image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Intern', 'Intern'), ('Temporary', 'Temporary')], max_length=50, verbose_name='Job type'),
        ),
    ]
