# Generated by Django 4.2.7 on 2023-11-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0002_spotlight_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_search.degree'),
            preserve_default=False,
        ),
    ]
