# Generated by Django 4.2.7 on 2023-11-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0004_organization_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
