# Generated by Django 4.2.7 on 2023-11-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0005_alter_spotlight_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'degree', 'verbose_name_plural': 'degrees'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='spotlight',
            options={'verbose_name': 'spotlight', 'verbose_name_plural': 'spotlights'},
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='degree name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Intern', 'Intern'), ('Temporary', 'Temporary')], max_length=50, verbose_name='job type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(unique=True, verbose_name='location name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(unique=True, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='img',
            field=models.URLField(verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
